Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
